config/routes.rb
Rails.application.routes.draw do
  
  # rootをログイン画面に設定
  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'users/dash_boards', to: 'users#index' 

  resource :users do
      resources :articles
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_user_new_permitted_parameters, if: :devise_controller?
  before_action :configure_user_update_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_dash_boards_path
  end

  private
    # Sign up
    def configure_user_new_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    # Edit User
    def configure_user_update_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit,  :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "記事を新規作成しました。"
      redirect_to users_articles_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "記事を編集しました。"
      redirect_to users_articles_url
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "記事：#{@article.title} を削除しました。"
    redirect_to users_articles_url
  end

  private
    def article_params
      params.require(:article).permit(:title, :content, :image, :image_cache)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, url: article_path, local: true) do |f| %>
 
  <%= render 'shared/error_messages', resource: article %>

  <!-- タイトル -->
  <%= f.label :title, class: "control-label" %>
  <%= f.text_field :title, class: "form-control" %>
  
  <!-- 内容 -->
  <%= f.label :content, class: "control-label" %>
  <%= f.text_area :content, class: "form-control" %>
  
  <!-- 画像 -->
  <%= f.label :image, class: "control-label" %><br/>
  <% if article.image? %>
    <%= image_tag(article.image.url(:thumb)) %><br/>
  <% end %>
  <%= f.file_field :image %><br/>
  <%= f.hidden_field :image_cache %>
  
  <div class="actions">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-article-submit" %>    
  </div>  

<% end %>

<%= link_to "戻る", :back %>

app/views/articles/edit.html.erb
<% provide(:button_text, '更新する') %>
<h2>記事の編集</h2>

<div class="row">
  <div class="w-50 mx-auto">
    <%= render 'form', article: @article, article_path: users_article_path(@article) %>
  </div>
</div>

app/views/articles/index.html.erb
<h2>記事一覧</h2>

<div class="actions">
  <%= link_to "記事新規作成", new_users_article_path, class: "btn btn-primary btn-article-new" %>
</div>

<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>詳細表示</th>
        <th>タイトル</th>
        <th>内容</th>
        <th>画像</th>
        <th>編集・削除</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <!-- 詳細ボタン -->
          <td><%= link_to "詳細", users_article_path(article), class: "btn btn-primary" %></td>
          <!-- タイトル -->
          <td><%= article.title %></td>
          <!-- 内容 -->
          <td><%= article.content %></td>
          <!-- 画像 -->
          <td><%= image_tag article.image.url(:thumb) if article.image.present? %></td>
          <!-- 編集ボタン・削除ボタン -->
          <td><%= link_to "修正", edit_users_article_path(article), class: "btn btn-success" %>
              <%= link_to "削除", users_article_path(article), method: :delete,
                    data: {confirm: "削除してよろしいですか？"},
                    class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 

</div>

app/views/articles/new.html.erb
<% provide(:button_text, '新規作成') %>
<h2>記事の新規作成</h2>

<div class="row">
  <div class="w-50 mx-auto">
    <%= render 'form', article: @article, article_path: users_articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<h2>記事詳細</h2>

<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>内容</th>
        <th>画像</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <!-- タイトル -->
        <td><%= @article.title %></td>
        <!-- 内容 -->
        <td><%= @article.content %></td>
        <!-- 画像 -->
        <td><%= image_tag @article.image.url(:thumb) if @article.image.present? %></td>
      </tr>
    </tbody>
  </table> 
  
  <!-- 編集ボタン・削除ボタン -->
  <div class="actions">
    <%= link_to "修正", edit_users_article_path(@article), class: "btn btn-success" %>
    <%= link_to "削除", users_article_path(@article), method: :delete,
          data: {confirm: "削除してよろしいですか？"},
          class: "btn btn-danger" %>
  </div>
  <div class="actions">
    <%= link_to "記事一覧に戻る", users_articles_path, class: "btn btn-primary btn-article-submit" %>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticlePostApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h2><%= t(".title") %></h2>

<% if user_signed_in? %>
  <h3><%= current_user.name %></h3>

  <div class="actions">
    <%= link_to "記事一覧", users_articles_path, class: "btn btn-primary btn-users-dashboard" %><br/>
    <%= link_to t(".edit_user"), edit_user_registration_path, class: "btn btn-primary btn-users-dashboard" %><br/>
    <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "btn btn-warning btn-users-dashboard" %>
  </div>  
<% else %>
  <div class="actions">
    <%= link_to t(".log_in"),  new_user_session_path, class: "btn btn-primary btn-users-dashboard" %><br/>
    <%= link_to t(".sign_up"), new_user_registration_path, class: "btn btn-primary btn-users-dashboard" %>
  </div>
<% end %>